// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwDB2SVZldErSzVdPzxP21yZrvte0cjZc',
    appId: '1:217363131757:web:3fe5fb70059bdfa3f43e64',
    messagingSenderId: '217363131757',
    projectId: 'social-media-app-43701',
    authDomain: 'social-media-app-43701.firebaseapp.com',
    storageBucket: 'social-media-app-43701.firebasestorage.app',
    measurementId: 'G-7K8RZ5BXK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZcnCbExQJCVAzKc2rbuPUwpvGImph-nQ',
    appId: '1:217363131757:android:84c3eb17cec86295f43e64',
    messagingSenderId: '217363131757',
    projectId: 'social-media-app-43701',
    storageBucket: 'social-media-app-43701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0_dEBKfz4P42ogRP-WmTgb_cO_pNIUY',
    appId: '1:217363131757:ios:21d07b7af714f125f43e64',
    messagingSenderId: '217363131757',
    projectId: 'social-media-app-43701',
    storageBucket: 'social-media-app-43701.firebasestorage.app',
    iosBundleId: 'com.example.sprintsFirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc0_dEBKfz4P42ogRP-WmTgb_cO_pNIUY',
    appId: '1:217363131757:ios:21d07b7af714f125f43e64',
    messagingSenderId: '217363131757',
    projectId: 'social-media-app-43701',
    storageBucket: 'social-media-app-43701.firebasestorage.app',
    iosBundleId: 'com.example.sprintsFirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwDB2SVZldErSzVdPzxP21yZrvte0cjZc',
    appId: '1:217363131757:web:45164dc446652c5ff43e64',
    messagingSenderId: '217363131757',
    projectId: 'social-media-app-43701',
    authDomain: 'social-media-app-43701.firebaseapp.com',
    storageBucket: 'social-media-app-43701.firebasestorage.app',
    measurementId: 'G-WS7QHXRJH1',
  );
}
